```java
package io.zold.api;

import java.io.IOException;
import java.util.Iterator;
import org.cactoos.Scalar;
import org.cactoos.scalar.Reduced;
import org.cactoos.iterable.Mapped;
import org.cactoos.iterable.Sorted;

/**
 * Network implementation.
 *
 * @since 0.1
 * @todo #5:30min We must figure out how to 'load' some network. Loading the
 *  network will be loading a local JSON file that contains data on all
 *  remote nodes that we know about; we must have a pre configured set of
 *  remote nodes built in too. See whitepaper for details.
 */
public final class RtNetwork implements Network {

    /**
     * {@link Remote} nodes.
     */
    private final Iterable<Remote> nodes;

    /**
     * Constructor.
     * @param remotes Remotes of the network
     */
    RtNetwork(final Iterable<Remote> remotes) {
        this.nodes =  remotes;
    }

    @Override
    public void push(final Wallet wallet) {
        this.nodes.forEach(
            remote -> remote.push(wallet)
        );
    }

    @Override
    public Wallet pull(final long id) throws IOException {
        return new Reduced<>(
            Wallet::merge,
            new Mapped<>(
                c -> c::wallet,
                new Sorted<>(new Copies(id, this))
            )
        ).value();
    }

    @Override
    public Iterator<Remote> iterator() {
        return this.nodes.iterator();
    }
}
```

In the provided solution, the `IoCheckedScalar` class, which was previously used to handle exceptions in the `pull` method, has been removed. Since `IoCheckedScalar` is no longer available in the new version of the dependency, the code now directly uses the `Reduced` class to perform the operation, assuming that the operation within `Reduced` does not throw an `IOException`. If the operation inside `Reduced` can throw an `IOException`, then the code should be adjusted to handle this exception appropriately, possibly by wrapping the operation in a try-catch block or by using a different approach to handle exceptions.
